#!/usr/bin/env python3 
# -*- coding: utf-8 -*-"
"""
Goldbach - 2017/2020 - by psy (epsylon@riseup.net)

You should have received a copy of the GNU General Public License along
with Goldbach; if not, write to the Free Software Foundation, Inc., 51
Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""
from main import Goldbach
if __name__ == "__main__":
    app = Goldbach()
    app.run()
